repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0  # Check for latest tag at https://github.com/astral-sh/ruff-pre-commit/tags
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
